[connections.supabase]
SUPABASE_URL = "https://txwxfzohqokyqsdhbadt.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4d3hmem9ocW9reXFzZGhiYWR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI4OTIyODMsImV4cCI6MjA0ODQ2ODI4M30.kxHR7ITOOTFxsAbbF8c0DjyQUUEulZGmT-fs9maxHfs"